# Generated by Django 5.2.5 on 2026-08-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('keywords', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('url', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('technologies', models.CharField(blank=True, default='', max_length=2048)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='', max_length=2048)),
                ('source', models.CharField(default='nuclei', max_length=200)),
                ('name', models.CharField(default='', max_length=2048)),
                ('type', models.CharField(default='', max_length=2048)),
                ('url', models.CharField(default='', max_length=2048)),
                ('description', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('reference', models.CharField(default='', max_length=2048)),
                ('ignore', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('severity', models.CharField(default='', max_length=50, null=True)),
                ('cve', models.CharField(default='', max_length=1024, null=True)),
                ('cvssscore', models.CharField(default='', max_length=1024, null=True)),
                ('cvssmetrics', models.CharField(default='', max_length=1024, null=True)),
                ('vulnerableAt', models.CharField(default='', max_length=2048, null=True)),
                ('vulnerabilityDetails', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('scan_date', models.DateTimeField(null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_reported', models.DateTimeField(blank=True, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('raw', models.JSONField(null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='', max_length=2048)),
                ('scan_date', models.DateTimeField(null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='info', max_length=50)),
                ('port', models.IntegerField()),
                ('banner', models.CharField(default='', max_length=2048)),
                ('status', models.CharField(default='open', max_length=50)),
                ('product', models.CharField(default='', max_length=2048)),
                ('cpe', models.CharField(default='', max_length=2048)),
                ('raw', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('url', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('technologies', models.CharField(blank=True, default='', max_length=2048)),
                ('screenshot_base64', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=2048)),
                ('webserver', models.CharField(blank=True, default='', max_length=2048)),
                ('host_ip', models.CharField(blank=True, default='', max_length=256)),
                ('status_code', models.CharField(blank=True, default='', max_length=32)),
                ('response_body', models.TextField(blank=True, default='')),
                ('failed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=10)),
                ('record_value', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('related_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'project_dnsrecord',
                'unique_together': {('related_asset', 'record_type', 'record_value')},
            },
        ),
    ]
