# Generated by Django 5.2.5 on 2026-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='response_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
