# Generated by Django 5.2.5 on 2026-09-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
