# Generated by Django 5.2.5 on 2026-08-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=2048)),
                ('source', models.CharField(default='', max_length=200)),
                ('tag', models.CharField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('link', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('type', models.CharField(default='domain', max_length=100)),
                ('subtype', models.CharField(default='', max_length=100)),
                ('scope', models.CharField(blank=True, default='external', max_length=100, null=True)),
                ('creation_time', models.DateTimeField()),
                ('last_seen_time', models.DateTimeField(blank=True, null=True)),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('cert_valid', models.BooleanField(default=True)),
                ('cert_wildcard', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=False)),
                ('ignore', models.BooleanField(default=False)),
                ('ipv4', models.CharField(blank=True, default='', max_length=512)),
                ('ipv6', models.CharField(blank=True, default='', max_length=1024)),
                ('owner', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(default=None, null=True)),
                ('registrant_info', models.JSONField(blank=True, default=None, null=True)),
                ('redirects_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('related_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keyword')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'project_asset',
            },
        ),
    ]
